Replace user input reading from cmd with a json rule configuration file.
bigfluffycookie/Project pull request #8
Opened 2022-10-13 10:02 UTC by bigfluffycookie

2022-10-14 11:17 UTC, rita-sonarsource commented on Exercise/Exercise/UserConfiguration.cs
> +        public string fileToAnalyze;
It's problematic to rely on fields being named exactly as the json, it's always better to explicitly declare them.
Also, look into serializing properties, instead of fields.

2022-10-14 11:18 UTC, rita-sonarsource commented on Exercise/Exercise/UserConfiguration.cs
> +        public Dictionary<string,string> rules;
For the sake of the exercise, how would you serialize a rule that has multiple parameters?

2022-10-14 11:19 UTC, rita-sonarsource commented on Exercise/Exercise/Rules/MaxFilePathLengthRule.cs
> +            if (!int.TryParse(ruleParam, out var maxAllowedFilePathLength))
It is a design smell that you changed the actual logic to support this. 
Always follow the rule that if it's a UI change, then nothing in the logic should be affected.
Assume that this code is written in an external library and you can't change it -- how would you handle it?

2022-10-14 11:20 UTC, rita-sonarsource commented on Exercise/Exercise/Program.cs
> +            var userConfiguration = GetUserConfiguration();
I'm sorry, I should've made it clear in the exercise that you should support both methods. This forces you to think about the int/string parameter :)

2022-10-14 11:21 UTC, rita-sonarsource requested changes
Please see my comments, try to limit the changes to UI layer only.

2022-10-14 11:41 UTC, bigfluffycookie commented on Exercise/Exercise/Rules/MaxFilePathLengthRule.cs
> +            if (!int.TryParse(ruleParam, out var maxAllowedFilePathLength))
The thing is, now that we have a json, it makes more sense to me that the rule itself is responsible for knowing what type it needs and doing the conversion.

but what I could do instead is have the json parameters be int instead of string

2022-10-14 11:52 UTC, bigfluffycookie commented on Exercise/Exercise/Program.cs
> +            var userConfiguration = GetUserConfiguration();
I don't understand what you mean here

2022-10-14 13:52 UTC, rita-sonarsource commented on Exercise/Exercise/Program.cs
> +            var userConfiguration = GetUserConfiguration();
Support both json and manually getting the information in the console, just like before.

2022-10-17 08:51 UTC, duncanp-sonar commented on Exercise/Exercise/Program.cs
> +        private static IInput GetInput()
Structurally, this approach makes sense: you've introduced an abstraction to hide how the configuration is provided (`IInput`), and you have two implementations, one from file and the other from user input.

Somewhere in the program you need to make a decision about which input method to use, which is handled in this method. Nothing else in the rest of the analyzer needs to know or care where the configuration is coming from - they can just use the `IInput` instance produced by this method.

2022-10-17 08:53 UTC, duncanp-sonar commented on Exercise/Exercise/Program.cs
> +                if (input == null)
Minor: what would you type in the console for the `input` to be `null` when using `ReadLine`?

2022-10-17 08:58 UTC, duncanp-sonar commented on Exercise/Exercise/Program.cs
> +                if (input == "j")
Let's think about the user experience: this approach works, but it means the caller always has to provide some input via the console.

The analyzer is a command line tool, so ideally we'd be able to automate calling it e.g. from a build pipeline.

Asking the caller for console input to specify the input method and then the name of the file makes calling the analyzer from a build pipeline difficult. How could you make the user experience more automation-friendly?

2022-10-17 09:06 UTC, duncanp-sonar commented on Exercise/Exercise/IInput.cs
> +    }
Naming consistency: these are all effectively `get` methods.

Alternative names to consider: 
```
... GetPathForFileToAnalyze();
... GetRulesToExecute();
... GetRuleParameters(...);
```

2022-10-17 09:06 UTC, bigfluffycookie commented on Exercise/Exercise/Program.cs
> +                if (input == null)
ctrl + c results in null

2022-10-17 09:07 UTC, bigfluffycookie commented on Exercise/Exercise/Program.cs
> +                if (input == "j")
The alterantive would be to have a file path where the program looks for ruleconfiguration files and if not it goes for manual input, is that what you mean?

2022-10-17 12:20 UTC, duncanp-sonar commented on Exercise/Exercise/InputFromUser.cs
> +        public string GetPathForFileToAnalyze() => ReadUserInputForFilePath(".txt");
UX: what prompt does the user now see in the console when entering the settings interactively?

2022-10-17 12:36 UTC, bigfluffycookie commented on Exercise/Exercise/InputFromUser.cs
> +        public string GetPathForFileToAnalyze() => ReadUserInputForFilePath(".txt");
Its on line 67 "Please input path for file to be analyzed"

2022-10-17 12:44 UTC, duncanp-sonar commented on Exercise/Exercise/InputFromJson.cs
> +                throw new Exception("Rule Configuration could not be Serialized");
"deserialized" rather "Serialized".

In general, it's seen as a best-practice to throw a more specific type of exception than `Exception` (the base class of all exceptions). Throwing a more specific error gives the calling code more of an opportunity to take remedial action if appropriate.

Sometimes there is already a predefined [standard exception](https://learn.microsoft.com/en-us/dotnet/api/system.exception?view=net-6.0#choosing-standard-exceptions) you can use, although VS makes it defining a custom exception quite straightforward.

Here, it doesn't matter too much.

2022-10-17 14:35 UTC, duncanp-sonar approved these changes
As discussed offline, it's probably worth committing this PR as-is now and then doing some of the refactorings we discussed offline.

2022-10-19 07:56 UTC, merged